-- SCRIPT PER PRODUZIONE CON RLS ABILITATO E POLICY SICUREZA
-- Esegui questo script solo per ambiente di produzione

-- 1. ELIMINA TUTTE LE TABELLE ESISTENTI
DROP TABLE IF EXISTS wheel_spins CASCADE;
DROP TABLE IF EXISTS wheel_spins2 CASCADE;
DROP TABLE IF EXISTS quiz_participants CASCADE;
DROP TABLE IF EXISTS wheel_eligibility CASCADE;
DROP TABLE IF EXISTS quiz_failures CASCADE;

-- 2. CREA TABELLA WHEEL_SPINS (versione produzione)
CREATE TABLE wheel_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    prize TEXT NOT NULL,
    prize_token TEXT,
    spin_result INTEGER,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CREA TABELLA QUIZ_FAILURES (versione produzione)
CREATE TABLE quiz_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    correct_answers INTEGER DEFAULT 0,
    total_questions INTEGER DEFAULT 7,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CREA INDICI PER PERFORMANCE
CREATE INDEX idx_wheel_spins_email ON wheel_spins(email);
CREATE INDEX idx_wheel_spins_created_at ON wheel_spins(created_at);
CREATE INDEX idx_quiz_failures_email ON quiz_failures(email);
CREATE INDEX idx_quiz_failures_created_at ON quiz_failures(created_at);

-- 5. ABILITA RLS (Row Level Security) PER SICUREZZA
ALTER TABLE wheel_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_failures ENABLE ROW LEVEL SECURITY;

-- 6. CREA POLICY PERMETTENDO SOLO INSERT E SELECT
-- Policy per wheel_spins
CREATE POLICY "Allow insert and select" ON wheel_spins
    FOR ALL USING (true)
    WITH CHECK (true);

-- Policy per quiz_failures  
CREATE POLICY "Allow insert and select" ON quiz_failures
    FOR ALL USING (true)
    WITH CHECK (true);

-- 7. VERIFICA STRUTTURA TABELLE
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name IN ('wheel_spins', 'quiz_failures')
ORDER BY table_name, ordinal_position;

-- 8. VERIFICA STATO RLS E POLICY
SELECT 
    n.nspname as schemaname,
    c.relname as tablename,
    c.relrowsecurity as rowlevelsecurity,
    false as forcerlspolicy  -- valore di default
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname IN ('wheel_spins', 'quiz_failures')
AND c.relkind = 'r'
ORDER BY tablename;

-- 9. VERIFICA POLICY CREATE
SELECT 
    schemaname,
    tablename,
    policyname,
    permissive,
    roles,
    cmd,
    qual
FROM pg_policies 
WHERE tablename IN ('wheel_spins', 'quiz_failures')
ORDER BY tablename, policyname;

-- 10. CONTA RIGHE (dovrebbero essere 0)
SELECT 
    'wheel_spins' as table_name, 
    COUNT(*) as row_count 
FROM wheel_spins
UNION ALL
SELECT 
    'quiz_failures' as table_name, 
    COUNT(*) as row_count 
FROM quiz_failures;

-- MESSAGGIO FINALE
SELECT 'Database produzione creato con RLS abilitato e policy sicurezza!' as status;
