-- SCRIPT SEMPLIFICATO PER RESET DATABASE
-- Esegui questo script nel tuo database Supabase per resettare tutto

-- 1. ELIMINA TUTTE LE TABELLE ESISTENTI
DROP TABLE IF EXISTS wheel_spins2 CASCADE;
DROP TABLE IF EXISTS wheel_spins CASCADE;
DROP TABLE IF EXISTS quiz_participants CASCADE;
DROP TABLE IF EXISTS wheel_eligibility CASCADE;

-- 2. CREA TABELLA WHEEL_SPINS (versione semplice e pulita)
CREATE TABLE wheel_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    prize TEXT NOT NULL,
    prize_token TEXT,
    spin_result INTEGER,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CREA TABELLA QUIZ_FAILURES (per salvare email quando si sbaglia)
DROP TABLE IF EXISTS quiz_failures;
CREATE TABLE quiz_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    correct_answers INTEGER DEFAULT 0,
    total_questions INTEGER DEFAULT 7,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CREA INDICI PER PERFORMANCE
CREATE INDEX idx_wheel_spins_email ON wheel_spins(email);
CREATE INDEX idx_wheel_spins_created_at ON wheel_spins(created_at);
CREATE INDEX idx_quiz_failures_email ON quiz_failures(email);
CREATE INDEX idx_quiz_failures_created_at ON quiz_failures(created_at);

-- 5. DISABILITA RLS (Row Level Security) PER PERMETTERE INSERIMENTI
ALTER TABLE wheel_spins DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_failures DISABLE ROW LEVEL SECURITY;

-- NOTA: NON aggiungere vincolo UNIQUE per evitare problemi RLS
-- L'anti-frode verrà gestito a livello applicativo

-- 6. VERIFICA STRUTTURA TABELLE
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name IN ('wheel_spins', 'quiz_failures')
ORDER BY table_name, ordinal_position;

-- 7. CONTA RIGHE (dovrebbero essere 0)
SELECT 
    'wheel_spins' as table_name, 
    COUNT(*) as row_count 
FROM wheel_spins
UNION ALL
SELECT 
    'quiz_failures' as table_name, 
    COUNT(*) as row_count 
FROM quiz_failures;

-- MESSAGGIO FINALE
SELECT 'Database resettato con successo! Tabelle wheel_spins e quiz_failures create.' as status;
